aliases:
  - &steps-for-xcode
    - checkout
    - run: |
        ( xcodebuild -scheme ObjectEncoder-Package test
          xcodebuild -scheme ObjectEncoder-Package test -sdk iphonesimulator -destination "name=iPhone 8"
          xcodebuild -scheme ObjectEncoder-Package test -sdk appletvsimulator -destination "name=Apple TV 4K"
          xcodebuild -scheme ObjectEncoder-Package build -sdk watchsimulator -destination "name=Apple Watch Series 3 - 38mm"
        ) | xcpretty -r junit
    - store_test_results:
        path: build/reports/
    - run: swift test
    - run: bash <(curl -s https://codecov.io/bash)

  - &steps-for-linux
    - checkout
    - run: swift test
    - run: mkdir -p build/reports/
    - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
    - store_test_results:
        path: build/reports/

  - &steps-for-linux-without-swiftlint
    - checkout
    - run: swift test
    - run: mkdir -p build/reports/

version: 2
jobs:

  xcode_9.0:
    macos:
      xcode: "9.0"
    steps: *steps-for-xcode

  xcode_9.1:
    macos:
      xcode: "9.1.0"
    steps: *steps-for-xcode

  xcode_9.2:
    macos:
      xcode: "9.2.0"
    steps: *steps-for-xcode

  xcode_9.3:
    macos:
      xcode: "9.3.0"
    steps: *steps-for-xcode

  linux_swift_4.0.2:
    docker:
      - image: norionomura/swiftlint:swift-4.0.2
    steps: *steps-for-linux

  linux_swift_4.0.3:
    docker:
      - image: norionomura/swiftlint:swift-4.0.3
    steps: *steps-for-linux

  linux_swift_4.1.0:
    docker:
      - image: norionomura/swiftlint:swift-4.1.0
    steps: *steps-for-linux

  linux_swift_4.1.1:
    docker:
      - image: norionomura/swiftlint:swift-4.1.1
    steps: *steps-for-linux

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9.0
      - xcode_9.1
      - xcode_9.2
      - xcode_9.3
      - linux_swift_4.0.2
      - linux_swift_4.0.3
      - linux_swift_4.1.0
      - linux_swift_4.1.1
