name: SwiftPM

on:
  push:
    branches: [master]
    paths: ['Sources/*', 'Tests/*', 'Package*', '.github/workflows/swiftpm.yml']
  pull_request:
    paths: ['Sources/*', 'Tests/*', 'Package*', '.github/workflows/swiftpm.yml']

jobs:
  macOS:
    strategy:
      matrix:
        xcode: ['9.4.1', '10', '10.1', '10.2.1', '10.3', '11']
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - run: swift -version
      - env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
        run: swift test --parallel

  Linux:
    strategy:
      matrix:
        tag: ['4.1', '4.2', '5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test --parallel
